services:
  db:
    container_name: "github-manager-db"
    platform: linux/x86_64
    image: postgres:latest
    environment:
      POSTGRES_USER: githubmanager
      POSTGRES_PASSWORD: githubmanager
    ports:
      - "5432:5432"
    volumes:
      - "github_manager_dbdata:/var/lib/postgresql/data"

  app:
    container_name: "github-manager-app"
    platform: linux/x86_64
    build: .
    environment:
      POSTGRES_USER: githubmanager
      POSTGRES_PASSWORD: githubmanager
      POSTGRES_HOST: db
      RAILS_ENV: development
      RACK_ENV: development
      REDIS_URL: redis://redis:6379
      LOG_LEVEL: debug
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - github_manager_bundle:/usr/local/bundle
    working_dir: /app
    stdin_open: true
    tty: true
    command: bundle exec rails s -p 3000 -b '0.0.0.0'

volumes:
  github_manager_dbdata:
  github_manager_bundle:
